### ISSUE TITLE
Hass and Raspberry cannot run the command

### ISSUE THREAD

**Issue by iShiva-Dev** [jrconlin/sunpower_hass#1]
`pi@raspberrypi:~/sunpower_hass $ python sunpower.py
Traceback (most recent call last):
  File "sunpower.py", line 3, in <module>
    from urllib import request
ImportError: cannot import name request
pi@raspberrypi:~/sunpower_hass $ python2 sunpower.py
Traceback (most recent call last):
  File "sunpower.py", line 3, in <module>
    from urllib import request
ImportError: cannot import name request
pi@raspberrypi:~/sunpower_hass $ python3 sunpower.py
Traceback (most recent call last):
  File "sunpower.py", line 5, in <module>
    from config import Config
ImportError: No module named 'config'
pi@raspberrypi:~/sunpower_hass $ `

pi@raspberrypi:~/sunpower_hass $ python sunpower.py
Traceback (most recent call last):
  File "sunpower.py", line 3, in <module>
    from urllib import request
ImportError: cannot import name request
pi@raspberrypi:~/sunpower_hass $ python2 sunpower.py
Traceback (most recent call last):
  File "sunpower.py", line 3, in <module>
    from urllib import request
ImportError: cannot import name request
pi@raspberrypi:~/sunpower_hass $ python3 sunpower.py
Traceback (most recent call last):
  File "sunpower.py", line 5, in <module>
    from config import Config
ImportError: No module named 'config'
pi@raspberrypi:~/sunpower_hass $ 

Appreciate by the component and its attention, thank you

**Comment by jrconlin** [comment]
Apologies for not making this a "proper" python module and adding a `setup.py`.

You'll need to run `pip install -r requirements.txt` to install the per-requisites. 

I'd also recommend running this in a python `virtualenv`. (See https://www.pythoncentral.io/how-to-install-virtualenv-python/ or just look for "[python virtualenv](https://www.google.pt/search?q=python+virtualenv)" 

This was more a goof around project for me. Eventually, I should finish it up and make it a proper home assistant module.

**Comment by iShiva-Dev** [comment]
thanks, is perfect
but
Is there any way the command line works in the Hassio?

**Comment by jrconlin** [comment]
Oh, probably. I really should just make it a real HomeAssistant extension, but I've not had a lot of time to do it. 

I'm not quite sure I follow what you mean by "command line", though. 

In my `configuration.yaml` file I've got:
```yaml
# solar:
sensor:
   - platform: command_line
     # Sunpower only updates every 5 minutes. No need to call more often.
     scan_interval: 300
     name: Solar Production
     # This uses the same python that runs HomeAssistant, and calls the script I've copied into
     # a sub directory 
     command: $HASS/bin/python $HOME/.homeassistant/scripts/sunpower.py
     unit_of_measurement: "kW"
```

I know that they recently rolled out the [HomeAssistant Command Line](https://www.home-assistant.io/hassio/commandline/), and I have no idea how well this works with that. I do know that it works with the HTTP interface, since  I can call it from another server:

```json
$ curl "http://home:8123/api/states/sensor.solar_production"
{"attributes": {"friendly_name": "Solar Production", "unit_of_measurement": "kW"}, "context": {"id": "c2b53359cfd944c19ac79d9ad7555e93", "user_id": null}, "entity_id": "sensor.solar_production", "last_changed": "2019-02-22T15:44:28.429890+00:00", "last_updated": "2019-02-22T15:44:28.429890+00:00", "state": "0.24"}
```
and that's good enough for what I need. 

Does that help?

(By the way, thanks for these questions. Again, when I get the time to write up proper documentation, they'll be really useful. Sorry for any confusion, but I'm very happy to provide whatever info I can.)
